spring.application.name=hostel_management

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect




attendance.network.enabled=true
attendance.network.allowed-subnets=152.57.0.0-152.57.255.255
attendance.network.allow-localhost=true
attendance.network.trust-proxy-headers=true
attendance.network.trusted-proxy-subnets=127.0.0.1/32
