spring.application.name=hostel_management

spring.datasource.url=jdbc:postgresql://localhost:5432/HostelManagement
spring.datasource.username=postgres
spring.datasource.password=123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080





attendance.network.enabled=true
attendance.network.allowed-subnets=150.0.0.0-180.0.0.0
attendance.network.allow-localhost=true
attendance.network.trust-proxy-headers=true
attendance.network.trusted-proxy-subnets=127.0.0.1/32
